import type { City } from "@/lib/types";

export const NEIGHBORHOODS_BY_CITY: Record<City, string[]> = {
  Lagos: [
    "Lekki Phase 1",
    "Chevron",
    "Magodo",
    "Gbagada",
    "Bode Thomas, Surulere",
    "Adeniran Ogunsanya, Surulere",
    "Adelabu, Surulere",
    "Aguda, Surulere",
    "Eric Moore, Surulere",
    "Iponri, Surulere",
    "Lawanson, Surulere",
    "Ojuelegba, Surulere",
    "Masha, Surulere",
    "Akerele, Surulere",
    "Census, Surulere",
    "Itire, Surulere",
    "Cole Street, Surulere",
    "Randle Avenue, Surulere",
    "Surulere (anywhere)",
  ],
  Abuja: ["Maitama", "Guzape", "Wuse 2"],
  "Port Harcourt": ["GRA Phase 2", "Old GRA", "Trans Amadi"],
};

export const AMENITY_OPTIONS = [
  "24hr power",
  "water treatment",
  "borehole",
  "generator",
  "inverter",
  "solar",
  "gated estate",
  "swimming pool",
  "gym",
  "bq",
  "ensuite rooms",
  "fitted kitchen",
  "pop ceiling",
  "balcony",
  "walk-in closet",
  "elevator",
  "cctv",
  "security guards",
  "children's play area",
];
