import type { City, Listing, ListingIntent } from "@/lib/types";
import type { ListingSourceAdapter } from "./adapter";

function hoursAgo(hours: number) {
  return new Date(Date.now() - hours * 60 * 60 * 1000).toISOString();
}

// Clearly-marked placeholder inventory standing in for real scraped data
// until source-site adapters are built (see CLAUDE.md open questions).
// scrapedAt is deliberately varied — a couple of entries are past the 72h
// freshness window, and one has no mandateContact, so buildShortlist's
// eligibility filter has something real to exclude.
const MOCK_LISTINGS: Listing[] = [
  {
    id: "mock-1",
    title: "3-Bed Detached Duplex, Lekki Phase 1",
    intent: "rent",
    city: "Lagos",
    neighborhood: "Lekki Phase 1",
    price: 6_500_000,
    bedrooms: 3,
    bathrooms: 4,
    amenities: ["24hr power", "water treatment", "gated estate"],
    photos: [],
    source: { site: "PropertyPro", url: "https://propertypro.ng/mock-1", scrapedAt: hoursAgo(5) },
    mandateContact: { name: "Adebayo Okafor", phone: "+234 802 123 4567" },
  },
  {
    id: "mock-2",
    title: "4-Bed Terrace, Chevron",
    intent: "rent",
    city: "Lagos",
    neighborhood: "Chevron",
    price: 8_000_000,
    bedrooms: 4,
    bathrooms: 4,
    amenities: ["generator", "gated estate", "swimming pool"],
    photos: [],
    source: { site: "NigeriaPropertyCentre", url: "https://nigeriapropertycentre.com/mock-2", scrapedAt: hoursAgo(20) },
    mandateContact: { name: "Funke Adeyemi", phone: "+234 803 234 5678", email: "funke.adeyemi@example.com" },
  },
  {
    id: "mock-3",
    title: "2-Bed Flat, Magodo Phase 2",
    intent: "rent",
    city: "Lagos",
    neighborhood: "Magodo",
    price: 2_800_000,
    bedrooms: 2,
    bathrooms: 2,
    amenities: ["24hr power", "gated estate"],
    photos: [],
    // Stale: last verified 90 hours ago, past the 72h freshness window.
    source: { site: "Jiji", url: "https://jiji.ng/mock-3", scrapedAt: hoursAgo(90) },
    mandateContact: { name: "Chinedu Eze", phone: "+234 804 345 6789" },
  },
  {
    id: "mock-4",
    title: "3-Bed Bungalow, Gbagada",
    intent: "lease",
    city: "Lagos",
    neighborhood: "Gbagada",
    price: 12_000_000,
    bedrooms: 3,
    bathrooms: 3,
    amenities: ["water treatment", "generator"],
    photos: [],
    // Fresh, but no mandate contact on file yet — excluded until one is added.
    source: { site: "Hutbay", url: "https://hutbay.com/mock-4", scrapedAt: hoursAgo(10) },
  },
  {
    id: "mock-5",
    title: "2-Bed Flat, Surulere",
    intent: "rent",
    city: "Lagos",
    neighborhood: "Surulere",
    price: 1_800_000,
    bedrooms: 2,
    bathrooms: 2,
    amenities: ["24hr power"],
    photos: [],
    source: { site: "PropertyPro", url: "https://propertypro.ng/mock-5", scrapedAt: hoursAgo(2) },
    mandateContact: { name: "Ngozi Umeh", phone: "+234 805 456 7890" },
  },
  {
    id: "mock-6",
    title: "5-Bed Detached House, Lekki Phase 1",
    intent: "buy",
    city: "Lagos",
    neighborhood: "Lekki Phase 1",
    price: 250_000_000,
    bedrooms: 5,
    bathrooms: 6,
    amenities: ["swimming pool", "bq", "gated estate", "24hr power"],
    photos: [],
    source: { site: "NigeriaPropertyCentre", url: "https://nigeriapropertycentre.com/mock-6", scrapedAt: hoursAgo(30) },
    mandateContact: { name: "Tunde Bakare", phone: "+234 806 567 8901", email: "tunde.bakare@example.com" },
  },
  {
    id: "mock-7",
    title: "3-Bed Terrace, Maitama",
    intent: "rent",
    city: "Abuja",
    neighborhood: "Maitama",
    price: 7_500_000,
    bedrooms: 3,
    bathrooms: 3,
    amenities: ["24hr power", "gated estate"],
    photos: [],
    source: { site: "PropertyPro", url: "https://propertypro.ng/mock-7", scrapedAt: hoursAgo(8) },
    mandateContact: { name: "Amina Bello", phone: "+234 807 678 9012" },
  },
  {
    id: "mock-8",
    title: "4-Bed Duplex, Guzape",
    intent: "buy",
    city: "Abuja",
    neighborhood: "Guzape",
    price: 180_000_000,
    bedrooms: 4,
    bathrooms: 5,
    amenities: ["swimming pool", "generator", "gated estate"],
    photos: [],
    source: { site: "Hutbay", url: "https://hutbay.com/mock-8", scrapedAt: hoursAgo(12) },
    mandateContact: { name: "Ibrahim Musa", phone: "+234 808 789 0123" },
  },
  {
    id: "mock-9",
    title: "2-Bed Flat, Wuse 2",
    intent: "rent",
    city: "Abuja",
    neighborhood: "Wuse 2",
    price: 3_500_000,
    bedrooms: 2,
    bathrooms: 2,
    amenities: ["24hr power", "water treatment"],
    photos: [],
    // Stale: last verified 100 hours ago, past the 72h freshness window.
    source: { site: "Jiji", url: "https://jiji.ng/mock-9", scrapedAt: hoursAgo(100) },
    mandateContact: { name: "Grace Okon", phone: "+234 809 890 1234" },
  },
  {
    id: "mock-10",
    title: "3-Bed Flat, GRA Phase 2",
    intent: "rent",
    city: "Port Harcourt",
    neighborhood: "GRA Phase 2",
    price: 4_000_000,
    bedrooms: 3,
    bathrooms: 3,
    amenities: ["generator", "gated estate"],
    photos: [],
    source: { site: "NigeriaPropertyCentre", url: "https://nigeriapropertycentre.com/mock-10", scrapedAt: hoursAgo(6) },
    mandateContact: { name: "Ekene Nwachukwu", phone: "+234 810 901 2345" },
  },
  {
    id: "mock-11",
    title: "4-Bed Semi-Detached, Old GRA",
    intent: "lease",
    city: "Port Harcourt",
    neighborhood: "Old GRA",
    price: 9_000_000,
    bedrooms: 4,
    bathrooms: 4,
    amenities: ["24hr power", "water treatment", "gated estate"],
    photos: [],
    source: { site: "PropertyPro", url: "https://propertypro.ng/mock-11", scrapedAt: hoursAgo(15) },
    mandateContact: { name: "Blessing Amadi", phone: "+234 811 012 3456", email: "blessing.amadi@example.com" },
  },
  {
    id: "mock-12",
    title: "3-Bed Bungalow, Trans Amadi",
    intent: "buy",
    city: "Port Harcourt",
    neighborhood: "Trans Amadi",
    price: 65_000_000,
    bedrooms: 3,
    bathrooms: 3,
    amenities: ["generator"],
    photos: [],
    source: { site: "Jiji", url: "https://jiji.ng/mock-12", scrapedAt: hoursAgo(40) },
    mandateContact: { name: "Emeka Chukwu", phone: "+234 812 123 4567" },
  },
];

export const mockAdapter: ListingSourceAdapter = {
  site: "Manual",
  async fetchListings({ city, intent }: { city: City; intent: ListingIntent }) {
    return MOCK_LISTINGS.filter((l) => l.city === city && l.intent === intent);
  },
};
