import type { City, Listing, ListingIntent } from "@/lib/types";
import type { ListingSourceAdapter } from "./adapter";

// Clearly-marked placeholder inventory standing in for real scraped data
// until source-site adapters are built (see CLAUDE.md open questions).
const MOCK_LISTINGS: Listing[] = [
  {
    id: "mock-1",
    title: "3-Bed Detached Duplex, Lekki Phase 1",
    intent: "rent",
    city: "Lagos",
    neighborhood: "Lekki Phase 1",
    price: 6_500_000,
    bedrooms: 3,
    bathrooms: 4,
    amenities: ["24hr power", "water treatment", "gated estate"],
    photos: [],
    source: { site: "PropertyPro", url: "https://propertypro.ng/mock-1", scrapedAt: new Date().toISOString() },
  },
  {
    id: "mock-2",
    title: "4-Bed Terrace, Chevron",
    intent: "rent",
    city: "Lagos",
    neighborhood: "Chevron",
    price: 8_000_000,
    bedrooms: 4,
    bathrooms: 4,
    amenities: ["generator", "gated estate", "swimming pool"],
    photos: [],
    source: { site: "NigeriaPropertyCentre", url: "https://nigeriapropertycentre.com/mock-2", scrapedAt: new Date().toISOString() },
  },
  {
    id: "mock-3",
    title: "2-Bed Flat, Magodo Phase 2",
    intent: "rent",
    city: "Lagos",
    neighborhood: "Magodo",
    price: 2_800_000,
    bedrooms: 2,
    bathrooms: 2,
    amenities: ["24hr power", "gated estate"],
    photos: [],
    source: { site: "Jiji", url: "https://jiji.ng/mock-3", scrapedAt: new Date().toISOString() },
  },
  {
    id: "mock-4",
    title: "3-Bed Bungalow, Gbagada",
    intent: "lease",
    city: "Lagos",
    neighborhood: "Gbagada",
    price: 12_000_000,
    bedrooms: 3,
    bathrooms: 3,
    amenities: ["water treatment", "generator"],
    photos: [],
    source: { site: "Hutbay", url: "https://hutbay.com/mock-4", scrapedAt: new Date().toISOString() },
  },
  {
    id: "mock-5",
    title: "2-Bed Flat, Surulere",
    intent: "rent",
    city: "Lagos",
    neighborhood: "Surulere",
    price: 1_800_000,
    bedrooms: 2,
    bathrooms: 2,
    amenities: ["24hr power"],
    photos: [],
    source: { site: "PropertyPro", url: "https://propertypro.ng/mock-5", scrapedAt: new Date().toISOString() },
  },
  {
    id: "mock-6",
    title: "5-Bed Detached House, Lekki Phase 1",
    intent: "buy",
    city: "Lagos",
    neighborhood: "Lekki Phase 1",
    price: 250_000_000,
    bedrooms: 5,
    bathrooms: 6,
    amenities: ["swimming pool", "bq", "gated estate", "24hr power"],
    photos: [],
    source: { site: "NigeriaPropertyCentre", url: "https://nigeriapropertycentre.com/mock-6", scrapedAt: new Date().toISOString() },
  },
  {
    id: "mock-7",
    title: "3-Bed Terrace, Maitama",
    intent: "rent",
    city: "Abuja",
    neighborhood: "Maitama",
    price: 7_500_000,
    bedrooms: 3,
    bathrooms: 3,
    amenities: ["24hr power", "gated estate"],
    photos: [],
    source: { site: "PropertyPro", url: "https://propertypro.ng/mock-7", scrapedAt: new Date().toISOString() },
  },
  {
    id: "mock-8",
    title: "4-Bed Duplex, Guzape",
    intent: "buy",
    city: "Abuja",
    neighborhood: "Guzape",
    price: 180_000_000,
    bedrooms: 4,
    bathrooms: 5,
    amenities: ["swimming pool", "generator", "gated estate"],
    photos: [],
    source: { site: "Hutbay", url: "https://hutbay.com/mock-8", scrapedAt: new Date().toISOString() },
  },
  {
    id: "mock-9",
    title: "2-Bed Flat, Wuse 2",
    intent: "rent",
    city: "Abuja",
    neighborhood: "Wuse 2",
    price: 3_500_000,
    bedrooms: 2,
    bathrooms: 2,
    amenities: ["24hr power", "water treatment"],
    photos: [],
    source: { site: "Jiji", url: "https://jiji.ng/mock-9", scrapedAt: new Date().toISOString() },
  },
  {
    id: "mock-10",
    title: "3-Bed Flat, GRA Phase 2",
    intent: "rent",
    city: "Port Harcourt",
    neighborhood: "GRA Phase 2",
    price: 4_000_000,
    bedrooms: 3,
    bathrooms: 3,
    amenities: ["generator", "gated estate"],
    photos: [],
    source: { site: "NigeriaPropertyCentre", url: "https://nigeriapropertycentre.com/mock-10", scrapedAt: new Date().toISOString() },
  },
  {
    id: "mock-11",
    title: "4-Bed Semi-Detached, Old GRA",
    intent: "lease",
    city: "Port Harcourt",
    neighborhood: "Old GRA",
    price: 9_000_000,
    bedrooms: 4,
    bathrooms: 4,
    amenities: ["24hr power", "water treatment", "gated estate"],
    photos: [],
    source: { site: "PropertyPro", url: "https://propertypro.ng/mock-11", scrapedAt: new Date().toISOString() },
  },
  {
    id: "mock-12",
    title: "3-Bed Bungalow, Trans Amadi",
    intent: "buy",
    city: "Port Harcourt",
    neighborhood: "Trans Amadi",
    price: 65_000_000,
    bedrooms: 3,
    bathrooms: 3,
    amenities: ["generator"],
    photos: [],
    source: { site: "Jiji", url: "https://jiji.ng/mock-12", scrapedAt: new Date().toISOString() },
  },
];

export const mockAdapter: ListingSourceAdapter = {
  site: "Manual",
  async fetchListings({ city, intent }: { city: City; intent: ListingIntent }) {
    return MOCK_LISTINGS.filter((l) => l.city === city && l.intent === intent);
  },
};
